name: 'terraform-ci'
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test
    
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      id: fmt
      run: terraform fmt 

    - name: Terraform Init
      id: init
      run: terraform init  

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'gcp'
        iac_dir: '.'
        only_warn: false 
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
 

    - name: Terraform Plan 
      id: plan
      run: terraform plan -no-color -input=false -out=tfplan
      continue-on-error: true 
     

    

    
      
